# Generated by Django 4.2.7 on 2024-01-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_gallerymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workermodel',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
    ]
