# Generated by Django 4.2.7 on 2024-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_categorymodel_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='ingredient',
            field=models.CharField(max_length=460, verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=400, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='pages.categorymodel', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='in_stock'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
